#!/usr/bin/env python3
"""
Generate the timezone picker in firmware/src/web_ui.h from shared/timezones.json.

The device, the settings page and the CLI all have to agree on which POSIX rule
belongs to which city. Keeping the list in one JSON file and generating the
copy that gets baked into the firmware is what stops them drifting.

    python tools/gen_timezones.py            rewrite the block in web_ui.h
    python tools/gen_timezones.py --check    exit 1 if it is out of date (CI)

Standard library only.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "shared" / "timezones.json"
TARGET = ROOT / "firmware" / "src" / "web_ui.h"

BEGIN = "/* TZLIST-BEGIN - generated by tools/gen_timezones.py, do not edit by hand */"
END = "/* TZLIST-END */"


def load_zones() -> list[dict]:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    zones = data["zones"]

    seen: set[str] = set()
    for z in zones:
        for key in ("group", "name", "label", "posix"):
            if not z.get(key):
                raise SystemExit(f"zone {z!r} is missing '{key}'")
        if z["name"] in seen:
            raise SystemExit(f"duplicate zone name: {z['name']}")
        seen.add(z["name"])
        # A quoted abbreviation like <+0330> must be balanced or newlib silently
        # falls back to UTC, which is a maddening bug to chase on the device.
        if z["posix"].count("<") != z["posix"].count(">"):
            raise SystemExit(f"unbalanced <> in POSIX rule for {z['name']}")
    return zones


def render(zones: list[dict]) -> str:
    """Emit the JS array as one entry per line: readable in a diff, and small
    enough that PROGMEM does not notice."""
    lines = [BEGIN, "var TZ=["]
    for z in zones:
        lines.append(
            "[{g},{n},{l},{p}],".format(
                g=json.dumps(z["group"]),
                n=json.dumps(z["name"]),
                l=json.dumps(z["label"]),
                p=json.dumps(z["posix"]),
            )
        )
    lines.append("];")
    lines.append(END)
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    start = text.find(BEGIN)
    stop = text.find(END)
    if start == -1 or stop == -1:
        raise SystemExit(f"markers not found in {TARGET}")
    return text[:start] + block + text[stop + len(END):]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify without writing (used by CI)")
    args = ap.parse_args()

    zones = load_zones()
    current = TARGET.read_text(encoding="utf-8")
    updated = splice(current, render(zones))

    if args.check:
        if current != updated:
            print("web_ui.h is out of date - run: python tools/gen_timezones.py",
                  file=sys.stderr)
            return 1
        print(f"ok - {len(zones)} zones in sync")
        return 0

    if current == updated:
        print(f"already up to date - {len(zones)} zones")
        return 0

    TARGET.write_text(updated, encoding="utf-8")
    print(f"wrote {len(zones)} zones into {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
